-- ====================================================================
-- 10_tables.sql
-- Tables, primary keys, foreign keys and indexes.
--
-- Source      : sql/OLTP/_raw/Superstore.sql (SQLPro export, 19-03-1402)
-- Target      : schema oltp — raw source data, read-only downstream
-- Modification: qualified into oltp, and the MySQL export's blanket
--               identifier quoting reduced to the names Postgres
--               actually requires it for (the columns). Statements,
--               column definitions and data rows are unchanged.
--
-- Tables are created in dependency order (product, customer, then
-- order and everything that references it). The DROP ... CASCADE
-- in front of each CREATE is from the export and makes this file
-- re-runnable on an existing database.
--
-- Heads-up: "order" is a reserved word. Schema-qualifying it is
-- enough (oltp.order parses fine), but an ad-hoc query that leans
-- on search_path must quote it: SELECT * FROM "order".
-- ====================================================================
-- ── product ─────────────────────────────────────────────────────
DROP TABLE IF EXISTS oltp.product CASCADE;
CREATE TABLE oltp.product (
  "Product ID" varchar(16) NOT NULL,
  "Product Name" varchar(128) DEFAULT NULL,
  "Category" varchar(16) DEFAULT NULL,
  "Sub-Category" varchar(16) DEFAULT NULL,
  PRIMARY KEY ("Product ID")
);

-- ── customer ────────────────────────────────────────────────────
DROP TABLE IF EXISTS oltp.customer CASCADE;
CREATE TABLE oltp.customer (
  "Customer ID" varchar(8) NOT NULL,
  "Customer Name" varchar(32) DEFAULT NULL,
  "Segment" varchar(16) DEFAULT NULL,
  PRIMARY KEY ("Customer ID")
);

-- ── order ───────────────────────────────────────────────────────
DROP TABLE IF EXISTS oltp.order CASCADE;
CREATE TABLE oltp.order (
  "Order ID" varchar(16) NOT NULL,
  "Customer ID" varchar(8) NOT NULL,
  "Order Priority" varchar(8) DEFAULT NULL,
  "Order Date" timestamp DEFAULT NULL,
  "Market" varchar(8) DEFAULT NULL,
  PRIMARY KEY ("Order ID"),
  CONSTRAINT order_ibfk_1 FOREIGN KEY ("Customer ID") REFERENCES oltp.customer ("Customer ID")
);

CREATE INDEX idx_order_customer_id ON oltp.order ("Customer ID");

-- ── order_detail ────────────────────────────────────────────────
DROP TABLE IF EXISTS oltp.order_detail CASCADE;
CREATE TABLE oltp.order_detail (
  "Row ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Order ID" varchar(16) DEFAULT NULL,
  "Product ID" varchar(16) DEFAULT NULL,
  "Sales" real DEFAULT NULL,
  "Quantity" integer DEFAULT NULL,
  "Discount" real DEFAULT NULL,
  "Profit" real DEFAULT NULL,
  "Shipping Cost" real DEFAULT NULL,
  PRIMARY KEY ("Row ID"),
  CONSTRAINT order_detail_ibfk_1 FOREIGN KEY ("Order ID") REFERENCES oltp.order ("Order ID"),
  CONSTRAINT order_detail_ibfk_2 FOREIGN KEY ("Product ID") REFERENCES oltp.product ("Product ID")
);

CREATE INDEX idx_order_detail_order_id ON oltp.order_detail ("Order ID");
CREATE INDEX idx_order_detail_product_id ON oltp.order_detail ("Product ID");

-- ── returned ────────────────────────────────────────────────────
DROP TABLE IF EXISTS oltp.returned CASCADE;
CREATE TABLE oltp.returned (
  "Order ID" varchar(16) NOT NULL,
  PRIMARY KEY ("Order ID"),
  CONSTRAINT returned_ibfk_1 FOREIGN KEY ("Order ID") REFERENCES oltp.order ("Order ID")
);

-- ── shipping ────────────────────────────────────────────────────
DROP TABLE IF EXISTS oltp.shipping CASCADE;
CREATE TABLE oltp.shipping (
  "Shipping ID" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Order ID" varchar(16) DEFAULT NULL,
  "Ship Date" timestamp DEFAULT NULL,
  "Ship Mode" varchar(16) DEFAULT NULL,
  "City" varchar(64) DEFAULT NULL,
  "State" varchar(64) DEFAULT NULL,
  "Country" varchar(32) DEFAULT NULL,
  "Region" varchar(16) DEFAULT NULL,
  PRIMARY KEY ("Shipping ID"),
  CONSTRAINT shipping_ibfk_1 FOREIGN KEY ("Order ID") REFERENCES oltp.order ("Order ID")
);

CREATE INDEX idx_shipping_order_id ON oltp.shipping ("Order ID");
