-- ====================================================================
-- 30_sequences.sql
-- Fast-forward the identity sequences past the loaded ids.
--
-- Source      : sql/OLTP/_raw/Superstore.sql (SQLPro export, 19-03-1402)
-- Target      : schema oltp — raw source data, read-only downstream
-- Modification: qualified into oltp, and the MySQL export's blanket
--               identifier quoting reduced to the names Postgres
--               actually requires it for (the columns). Statements,
--               column definitions and data rows are unchanged.
--
-- The data files insert explicit values into the GENERATED BY
-- DEFAULT AS IDENTITY columns, which leaves each sequence still
-- sitting at 1. Without this, the next insert collides with an
-- existing row. Must run after every data file.
-- ====================================================================
SELECT setval(pg_get_serial_sequence('oltp.order_detail', 'Row ID'), (SELECT COALESCE(MAX("Row ID"), 1) FROM oltp.order_detail));
SELECT setval(pg_get_serial_sequence('oltp.shipping', 'Shipping ID'), (SELECT COALESCE(MAX("Shipping ID"), 1) FROM oltp.shipping));
